seed: 123
device: 1 # currently no distributed training
batch_size: 64
model:
  vocab_size: 10_000
  context_length: 256
  d_model: 512 # 768 (dimensions used in many small Transformer papers)
  d_ff: 1344 # ~8/3 d_model; 64x, which is good for GPU performance.
  rope_theta: 10_000
  num_layers: 4
  num_heads: 16 # 17M non-embedding parameters
  dtype: float32
  load_prefix: "~/ai_projects/Natural_Language_Processing/p2_transformers/weights/TinyStoriesV2-GPT4/RTX5090"
  load_name: "exp_bs_64/cosine/steps_20000/warmup_1000/Lion/lrmax0.0003_lrmin2.9999999999999997e-05_wdecay0.005/dmodel_512_dff_1344_numlayers_4_numheads_16_cntx_256/20250820_112759/ckpt_best.pt"
data:
  num_samples: -1
  path: '~/ai_projects/data/TinyStoriesV2-GPT4/tokenized/valid.npy'