name: llms
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - numpy=2.3* # 2.3.1
  - einops=0.8.1
  - tqdm=4* # 4.67.1
  - termcolor # 3.1.0
  - psutil # 7.0.0
  - pyyaml # 6.0.2
  - regex # 2024.11.6
  - tensorboard=2.19.0
  - pip:
      - torch==2.7.0+cu128
